# Postgres - DB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13.16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: fake-shop
            - name: POSTGRES_USER
              value: fake-shop
            - name: POSTGRES_PASSWORD
              value: pg12345
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
# App Web
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-shop
spec:
  replicas: 4
  selector:
    matchLabels:
      app: fake-shop
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
      labels:
        app: fake-shop
    spec:
      containers:
        - name: fake-shop
          image: augustokemp/fake-shop:v2
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_USER
              value: fake-shop
            - name: DB_PASSWORD
              value: pg12345
            - name: DB_NAME
              value: fake-shop
            - name: DB_PORT
              value: "5432"
            - name: FLASK_APP
              value: index.py
---
apiVersion: v1
kind: Service
metadata:
  name: fake-shop
spec:
  selector:
    app: fake-shop
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer
