name: CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to Git Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Autenticar no Docker Hub
        run: echo "Executando Docker login"

      - name: Contrução da Imagem Docker
        run: echo "Executando Docker build"

      - name: Envio da Imagem Docker
        run: echo "Executando Docker push"
  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Autenticar na AWS
        run: echo "Executando AWS configure"

      - name: Configurar o kubectl
        run: echo "Executando aws eks update-kubeconfig"

      - name: Deploy dos manifestos no Kubernetes
        run: echo "Executando comando kubectl apply"
